### ISSUE TITLE
Foxglove does not plot data

### ISSUE THREAD

**Issue by mhl787156** [StarlingUAS/ProjectStarling#147]
Previous none version of rosbridge suite is v0.1.0. There is problem with the latest version referred to in #146 .

This issue looks at v0.1.0 and tries to identify why foxglove is not plotting any data, but succeeeds at showin data.

An issue has been raised https://github.com/foxglove/studio/issues/2697 but it looks like it might be something from ourside.

**Comment by mhl787156** [comment]
Okay, further investigation appears to show that gazebo uses its own times format compared to the rest of ROS. When gazebo is started, it starts its own `/clock` using `rosgraph_msgs/msg/Clock`. This appears to reset all time in the simulation and break how foxglove shows plotting data for everything else. 
Unfortunately not entirely sure how to fix, but have updated the issue with the Foxglove guys so we shall see what they say https://github.com/foxglove/studio/issues/2697

**Comment by mhl787156** [comment]
Okay further further investigation seems that this should be solvable through remapping `/clock` into something else, and then remapping it back for mavros on the ros1 side so it doesnt pollute the ros2 list of topics. This may be more annoying when we move to ROS2 but we will cross that line then.

**Comment by rob-clarke** [comment]
I feel like these are potentially related:
https://github.com/foxglove/studio/pull/1293
https://github.com/foxglove/studio/pull/2322
