### ISSUE TITLE
RVIZ Compatibility 

### ISSUE THREAD

**Issue by mhl787156** [StarlingUAS/ProjectStarling#26]
Investigate the use of webviz and other web tools.

**Comment by mhl787156** [comment]
Currently eyeing up [webviz](https://github.com/cruise-automation/webviz) as it looks extremely well put together and should be compatible with the ros2-web-bridge. From what I understand, webviz itself is separate from ROS, and the UI can be configured to listen to a web bridge, rosbag or anything else. 

Question is whether the container running webviz should have its own web bridge? Or whether it should make use of the one exposed by starling-ui? Unsure if there might be port collision problems or otherwise. 

Opened a new branch pr-webviz for testing.

**Comment by georgiostzoum** [comment]
Hey Mickey thank you for taking a look so I agree that it looks really good and promising. I was trying to get them to communicate last week without success. I will be trying to do something to connect them following a tutorial that I found. Hopefully I will have something useful soon! 

Regarding your question and if I understand it correctly, they can communicate at a local host level or over a network. Maybe from a users perspective it would be easier to get it locally as it seems simpler. I am looking into this:
https://medium.com/@ben.k.muller/running-multiple-docker-containers-that-communicate-via-localhost-6f029caeb19c

**Comment by mhl787156** [comment]
@rob-clarke thoughts on having a single web bridge running in a container which all web-apps connect to? versus having one for each web application?

**Comment by rob-clarke** [comment]
I don't see any major problems. Two things we will need to be careful of:

1. As per https://github.com/RobotWebTools/ros2-web-bridge/issues/110, any custom messages need to be installed before `rclnodejs` to ensure that the messages are generated. Therefore, any user-defined types won't work with a common image.

2. We'll need to carefully control where the container is running to ensure that a vehicle running out of battery doesn't kill the UIs. I'm not sure what the response time is for k8s to redeploy a node and how clunky reestablishing the ws connections from the clients would be.

**Comment by mhl787156** [comment]
Cool, that will be the next job I suppose.

I wonder for 1. since it seems that you can add .msg locations to `AMENT_PREFIX_PATH` whether we can have all of our custom msgs and srvs all in one place - some network storage device/volume? Would that work with standard ROS2 builds as well?

**Comment by rob-clarke** [comment]
What are you hoping to achieve with network storage for message definitions? Why not just a repo? Typically custom messages need to be present at compile time, so this only a problem when building the images. At present the only significant addition to the standard message set is `mavros_msgs`, which will be available as a package for ROS2 in the near future. At that point declaring a dependency on `mavros_msgs` will be sufficient so long as it is installed before any packages that may generate code for custom messages.

If users need custom message types in the UI, they will be modifying the UI stack, so will require a separate set of containers. It doesn't seem too awful to ask them to add their own bridge container either as a replacement or alongside the existing one.

**Comment by mhl787156** [comment]
@georgiostzoum After looking at the starling-ui docker, it's already the basic web bridge. We also consider it one of the 'core' starling containers so it's always run anyway - so there's no need to take it out into its own container! 

If you start starling by `make run` or `./run_k3s.sh`, (or `./script/start_starling_base.sh`) They all start the web bridge on `<host machine ip>: 9090`.

**Comment by georgiostzoum** [comment]
Hey guys after some research with the help of @mhl787156 it seems that we can't  use Webviz as it doesn't support ROS2 as per this issue: https://github.com/cruise-automation/webviz/issues/348
Seems that a potential solution would be to make a GUI on a docker container and use that.

**Comment by mhl787156** [comment]
Suggestion is we look into running rviz (and maybe gazebo?) gui's locally directly from the container. Refer to the following article: [running gui application on docker container](https://rootritesh.medium.com/running-gui-application-on-docker-container-91a860f9b431). Older posts refer to possibly needing nvidia container elemengs (see this link)[https://answers.ros.org/question/301056/ros2-rviz-in-docker-container/] but I don't know if these instructions are still up to date. 

As a side question, this may break multiplatform support. I'm not sure how native windows will react (wsl2 backed should be fine)

**Comment by rob-clarke** [comment]
Is there the option of looking at porting webviz? Would be a significant undertaking but I can imagine there being a good community looking to help

**Comment by mhl787156** [comment]
> Hey guys after some research with the help of @mhl787156 it seems that we can't use Webviz as it doesn't support ROS2 as per this issue: [cruise-automation/webviz#348](https://github.com/cruise-automation/webviz/issues/348)
> Seems that a potential solution would be to make a GUI on a docker container and use that.

According to this webiz issue, it looks like it might be a significant undertaking which not a lot of people seem to be working on. I've done some extensive searching and there are no ROS2 visualisation tools apart from rviz so there must definitely be a need for it. It's just a question of whether it is critical to Starling. I think in our case its a shame webviz isn't working but rviz is probably good enough - if we could get an intern however, this would be a great project!

**Comment by mhl787156** [comment]
Closing, foxglove is a good and tested alternative for now!
