### ISSUE TITLE
Minimize sudo need for run_k3s

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/ProjectStarling#83]
It feels risky that run_k3s nearly always asks for your password for a sudo.  How about moving the install to a separate script and having the routine run_k3s.sh script just do a sanity check and crashing out with a "first run install_k3s" message if you haven't got what you need?  Then run_k3s never invokes sudo.

**Comment by mhl787156** [comment]
Resolved with the new Starling CLI in https://github.com/StarlingUAS/Murmuration/pull/4 

Only installation of systems require sudo.
