### ISSUE TITLE
Enable custom starting location

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/ProjectStarling#89]
Provide facility, or at least document since it’s probably already there, to customise the starting latitude and longitude.  Specifically I’d like to be able to start a drone - only one - at Fenswood.

**Comment by mhl787156** [comment]
@rob-clarke this is solved by ardupilot-gazebo correct? #72 
The sitl exposes the following env variables as [default](
- `ENV AP_HOME 51.4235413,-2.6708488,50,250`
- `ENV AP_OFFSET_X 0`
- `ENV AP_OFFSET_Y 0`
