### ISSUE TITLE
Target spawning for group project scenario

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/ProjectStarling#99]
Please create a utility to spawn the "target" and "hotspot" markers in the group project Fenswood simulation according to the specification described in the attached [draft briefing document](https://github.com/UoBFlightLab/ProjectStarling/files/7328795/briefing_document_draft.pdf).

Can use the [target spawning script](https://github.com/arthurrichards77/farscope_group_project/blob/main/scripts/setup/spawn_targets.py) from the FARSCOPE group project as an example.  While that case used a custom mesh, I'd be happy for the targets in this case to be simple built-in primitives, e.g. cylinders or boxes.  This should simplify containerization.

You can find the FARSCOPE target model in URDF form [here](https://github.com/arthurrichards77/farscope_group_project/tree/main/models/target).  Note in that project, the [launch file](https://github.com/arthurrichards77/farscope_group_project/blob/main/launch/challenge/farscope_group_challenge_gazebo.launch) loaded the URDF into a parameter and then the spawning script read the parameter and streamed it as text into Gazebo's spawn service.

Happy for spawning to take a simpler approach than the full complexity talked about in the briefing document.  You could just use cylinders to fill in a segment of the crater annulus region, and then fill one end of that with a red cylinder as a single hotspot.  Keep it simple to avoid the chance of a difficult or even impossible scenario, where the yellow target was totally filled with red hotspots.

**Comment by mhl787156** [comment]
This has been solved by https://github.com/StarlingUAS/FenswoodScenario/pull/8
